/*
 * harness.c - the recompiler conformance harness.
 *
 * Each program in Musashi's 68000 test corpus (ext/musashi/test/mc68000,
 * MIT) is recompiled at build time by m68krecomp and linked in here. The
 * harness gives each one the memory map Musashi's own test driver uses and
 * runs it natively: the program exercises one instruction family across
 * operand sizes, addressing modes and flag cases, and reports by writing
 * to TEST_PASS_REG ($100004) or TEST_FAIL_REG ($100000).
 *
 * A test passes when it reports pass and never fail, reaching every
 * instruction through recompiled code. Each program is also run in
 * Musashi as a 68000 (the reference column), so a program the reference
 * itself fails is a corpus expectation, not a recompiler bug. The
 * process exits non-zero if fewer tests pass than --min-pass, which CI
 * sets from tests/conformance/BASELINE so a regression fails the build.
 *
 *   $000000-$00FFFF RAM (vectors, stack at $3F0)
 *   $010000-$04FFFF the test program
 *   $100000         test device: pass/fail/putchar
 *   $300000-$30FFFF RAM
 */
#include <neogeorecomp/bus.h>
#include <neogeorecomp/cpu.h>
#include <neogeorecomp/neogeo.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "m68k.h"

uint8_t *ng_rmap[256];
uint8_t *ng_wmap[256];

static uint8_t s_ram0[0x10000], s_rom[0x40000], s_ram3[0x10000];
static int s_pass, s_fail;

/* The test device and unmapped space. 32-bit writes arrive as two 16-bit
 * halves; count each report once, on its low half. */
uint8_t ng_r8_slow(uint32_t a) { (void)a; return 0; }
uint16_t ng_r16_slow(uint32_t a) { (void)a; return 0; }
void ng_w8_slow(uint32_t a, uint8_t v) { if (a == 0x100014) putchar(v); }
void ng_w16_slow(uint32_t a, uint16_t v) {
    (void)v;
    if (a == 0x100002) s_fail++;
    if (a == 0x100006) s_pass++;
}

static const char *s_current;
void ng_bad_dispatch(uint32_t pc) {
    fprintf(stderr, "%s: routine entered at $%06X, which it does not contain\n", s_current, pc);
    exit(3);
}

/* Musashi reads and writes the same maps the recompiled code uses. */
unsigned int m68k_read_memory_8(unsigned int a) { return ng_r8(a); }
unsigned int m68k_read_memory_16(unsigned int a) { return ng_r16(a); }
unsigned int m68k_read_memory_32(unsigned int a) { return ng_r32(a); }
unsigned int m68k_read_immediate_16(unsigned int a) { return ng_r16(a); }
unsigned int m68k_read_immediate_32(unsigned int a) { return ng_r32(a); }
unsigned int m68k_read_pcrelative_8(unsigned int a) { return ng_r8(a); }
unsigned int m68k_read_pcrelative_16(unsigned int a) { return ng_r16(a); }
unsigned int m68k_read_pcrelative_32(unsigned int a) { return ng_r32(a); }
unsigned int m68k_read_disassembler_16(unsigned int a) { return ng_r16(a); }
unsigned int m68k_read_disassembler_32(unsigned int a) { return ng_r32(a); }
void m68k_write_memory_8(unsigned int a, unsigned int v) { ng_w8(a, (uint8_t)v); }
void m68k_write_memory_16(unsigned int a, unsigned int v) { ng_w16(a, (uint16_t)v); }
void m68k_write_memory_32(unsigned int a, unsigned int v) { ng_w32(a, v); }

/* ---- the corpus, generated by CMake ---- */
#define T(name) \
    extern const ng_func_entry_t t_##name##_ng_recomp_table[]; \
    extern const size_t t_##name##_ng_recomp_count;
#include "conformance_list.h"
#undef T

typedef struct {
    const char *name;
    const ng_func_entry_t *table;
    const size_t *count;
} test_t;

static const test_t k_tests[] = {
#define T(name) {#name, t_##name##_ng_recomp_table, &t_##name##_ng_recomp_count},
#include "conformance_list.h"
#undef T
};

/* ---- dispatch ---- */

#define HASH 65536
static struct { uint32_t addr; ng_func_t fn; } s_hash[HASH];

static void build_hash(const ng_func_entry_t *t, size_t n) {
    memset(s_hash, 0, sizeof(s_hash));
    for (size_t i = 0; i < n; i++) {
        uint32_t h = (t[i].addr * 2654435761u) & (HASH - 1);
        while (s_hash[h].fn) h = (h + 1) & (HASH - 1);
        s_hash[h].addr = t[i].addr;
        s_hash[h].fn = t[i].fn;
    }
}

static ng_func_t lookup(uint32_t a) {
    a &= 0xFFFFFF;
    uint32_t h = (a * 2654435761u) & (HASH - 1);
    while (s_hash[h].fn) {
        if (s_hash[h].addr == a) return s_hash[h].fn;
        h = (h + 1) & (HASH - 1);
    }
    return NULL;
}

static int load(const test_t *t, const char *dir) {
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s.bin", dir, t->name);
    FILE *f = fopen(path, "rb");
    if (!f) { printf("  %-16s SKIP (cannot open %s)\n", t->name, path); return -1; }
    memset(s_rom, 0, sizeof(s_rom));
    size_t n = fread(s_rom, 1, sizeof(s_rom), f);
    fclose(f);
    (void)n;

    memset(s_ram0, 0, sizeof(s_ram0));
    memset(s_ram3, 0, sizeof(s_ram3));
    for (int v = 0; v < 64; v++) {   /* every vector 0xDEADBEEF, as Musashi's driver does */
        s_ram0[v * 4] = 0xDE; s_ram0[v * 4 + 1] = 0xAD; s_ram0[v * 4 + 2] = 0xBE; s_ram0[v * 4 + 3] = 0xEF;
    }
    static const uint8_t boot[8] = {0, 0, 0x03, 0xF0, 0, 0x01, 0, 0};   /* SSP $3F0, PC $10000 */
    memcpy(s_ram0, boot, sizeof(boot));
    memset(ng_rmap, 0, sizeof(ng_rmap));
    memset(ng_wmap, 0, sizeof(ng_wmap));
    ng_rmap[0x00] = ng_wmap[0x00] = s_ram0;
    for (int p = 0; p < 4; p++) ng_rmap[0x01 + p] = s_rom + p * 0x10000;
    ng_rmap[0x30] = ng_wmap[0x30] = s_ram3;
    s_pass = s_fail = 0;
    return 0;
}

/* The reference: the same program in Musashi as a plain 68000. */
static int run_musashi(const test_t *t, const char *dir) {
    if (load(t, dir)) return 0;
    m68k_pulse_reset();
    for (int i = 0; i < 100 && !(s_pass || s_fail); i++) m68k_execute(0x100000);
    return s_pass > 0 && s_fail == 0;
}

static int run(const test_t *t, const char *dir, int verbose, int ref) {
    if (load(t, dir)) return 0;
    build_hash(t->table, *t->count);
    memset(&ng_cpu, 0, sizeof(ng_cpu));
    ng_cpu.s = 1; ng_cpu.ipl = 7;
    ng_cpu.a[7] = 0x3F0;
    ng_cpu.pc = 0x10000;
    ng_cycles = 0;
    ng_icount = 0;
    s_current = t->name;

    const char *why = NULL;
    while (!ng_cpu.stopped) {
        if (ng_icount > 200000000u) { why = "did not finish"; break; }
        ng_func_t fn = lookup(ng_cpu.pc);
        if (!fn) { why = "reached code the recompiler did not find"; break; }
        ng_next_event = ng_cycles + 1000000;
        fn();
    }
    int ok = !why && s_pass > 0 && s_fail == 0;
    if (!ok || verbose) {
        const char *r = ref ? "reference pass" : "reference FAIL";
        if (why) printf("  %-16s FAIL  %s (pc $%06X); %s\n", t->name, why, ng_cpu.pc & 0xFFFFFF, r);
        else printf("  %-16s %s  %llu instructions; %s\n", t->name, ok ? "pass" : "FAIL",
                    (unsigned long long)ng_icount, r);
    }
    return ok;
}

int main(int argc, char **argv) {
    const char *dir = NULL, *only = NULL;
    int min_pass = -1, verbose = 0;
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--corpus") && i + 1 < argc) dir = argv[++i];
        else if (!strcmp(argv[i], "--min-pass") && i + 1 < argc) min_pass = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--only") && i + 1 < argc) only = argv[++i];
        else if (!strcmp(argv[i], "-v")) verbose = 1;
        else {
            fprintf(stderr, "usage: %s --corpus DIR [--min-pass N] [--only NAME] [-v]\n", argv[0]);
            return 2;
        }
    }
    if (!dir) { fprintf(stderr, "error: --corpus is required\n"); return 2; }
    m68k_init();
    m68k_set_cpu_type(M68K_CPU_TYPE_68000);
    int total = 0, passed = 0, ref_passed = 0;
    for (size_t i = 0; i < sizeof(k_tests) / sizeof(k_tests[0]); i++) {
        if (only && strcmp(only, k_tests[i].name)) continue;
        total++;
        int ref = run_musashi(&k_tests[i], dir);
        ref_passed += ref;
        passed += run(&k_tests[i], dir, verbose, ref);
    }
    printf("conformance: %d/%d 68000 test programs pass recompiled (reference interpreter: %d/%d)\n",
           passed, total, ref_passed, total);
    if (min_pass >= 0 && passed < min_pass) {
        printf("REGRESSION: %d passing is below the baseline of %d\n", passed, min_pass);
        return 1;
    }
    return 0;
}
